"""add_order_and_goods

Revision ID: 0ab0185fa7f8
Revises: c57600b12481
Create Date: 2023-01-20 15:35:33.914848

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0ab0185fa7f8'
down_revision = 'c57600b12481'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('good',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price_usd', sa.NUMERIC(), nullable=False),
    sa.Column('price_gel', sa.NUMERIC(), nullable=True),
    sa.Column('price_rub', sa.NUMERIC(), nullable=True),
    sa.Column('price_eur', sa.NUMERIC(), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('client_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('deliver', 'selftake', name='ordertype'), nullable=False),
    sa.Column('delivery_lon', sa.Float(), nullable=True),
    sa.Column('delivery_lat', sa.Float(), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_good',
    sa.Column('order_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('good_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['good_id'], ['good.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_good')
    op.drop_table('order')
    op.drop_table('good')
    # ### end Alembic commands ###
