"""add_refresh_token_table

Revision ID: c05272d8769c
Revises: c57600b12481
Create Date: 2023-01-06 21:46:30.329541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c05272d8769c'
down_revision = 'c57600b12481'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
