name: testing

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: chckout repo
      uses: actions/checkout@v2
    - name: build app
      run: make build_dev
    - name: run db
      run: make run_db
    - name: run tests
      run: make tests