name: testing

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    - name: build app
      run: make build_dev
    - name: run db
      run: make run_db
    - name: list dir os
      run: ls -la
    - name: list dir docker
      run: make ls
    - name: run tests
      run: make test
